version: "3.8"
services:
  mysql:
    image: mysql:5.7.35
    hostname: mysql.dev.home
    networks:
      devnet:
        ipv4_address: 172.18.0.4
    container_name: mysql
    volumes:
      - ./config/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./mysql_data:/var/lib/mysql
    env_file:
      - vars.env
    ports:
      - "3306:3306"
    restart: unless-stopped

  phpmyadmin_php:
    image: php-custom:8.0.10-fpm
    networks:
      devnet:
        ipv4_address: 172.18.0.6
    container_name: phpmyadmin_php
    restart: unless-stopped
    volumes:
      - ./www/:/var/www/html/
      - ./config/php.ini:/usr/local/etc/php/php.ini

  phpmyadmin_nginx:
    image: nginx-custom:1.21.1
    networks:
      devnet:
        ipv4_address: 172.18.0.5
    container_name: phpmyadmin_nginx
    hostname: phpmyadmin.dev.home
    restart: unless-stopped
    links:
      - phpmyadmin_php
    volumes:
      - /media/adam/DOCKER/BASIC_IMAGES/OPENSSL_CERTS/dev.home:/etc/nginx/ssl/
      - ./config/www.conf:/etc/nginx/conf.d/default.conf
      - ./www/:/var/www/html/
      - ./config/config.inc.php:/var/www/html/config.inc.php
      - ./phpmyadmin_data/upload:/var/www/upload
      - ./phpmyadmin_data/save:/var/www/save

    
networks:
  devnet:
    external: true